//! Public statements/proofs generated by the maintained holder and verified by
//! the actual shipped worker. No pre-approved verdict or accepting substitute.
#![allow(dead_code)]
use cblc::{Error, accounting::*, accounting_service::{ProcessAccountVerifier, ProcessVerifierConfig}};
use data_encoding::{BASE64URL_NOPAD as B64, HEXLOWER};
use ed25519_dalek::Signer;
use serde::Deserialize;
use std::{
    collections::BTreeMap,
    path::PathBuf,
    sync::{Arc, Mutex, OnceLock, atomic::{AtomicUsize, Ordering}},
    time::Duration,
};

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Record {
    pub statement: AccountStatement,
    pub proof: String,
    pub proof_scope: AccountProofScope,
}

fn directory() -> PathBuf {
    std::env::var("CBLC_PROOF_DIRECTORY")
        .expect("CI must generate real holder proofs")
        .into()
}

pub fn record(index: usize) -> Record {
    static RECORDS: OnceLock<Vec<Record>> = OnceLock::new();
    RECORDS.get_or_init(|| {
        let bytes = std::fs::read(directory().join("ledger-records.json")).unwrap();
        let records: Vec<Record> = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(records.len(), 5);
        records
    })[index].clone()
}

pub fn request(index: usize, id: u8, fixture: &super::Fixture) -> AccountRequest {
    let record = record(index);
    let mut request = AccountRequest {
        issued_at: record.statement.now,
        statement: record.statement,
        request_id: [id; 32],
        proof_scope: record.proof_scope,
        chat_public_key: B64.encode(&fixture.device.verifying_key().to_bytes()),
        expires_at: 180,
        proof: HEXLOWER.decode(record.proof.as_bytes()).unwrap(),
        signature: String::new(),
    };
    request.signature = B64.encode(&fixture.device.sign(&account_request_bytes(&request).unwrap()).to_bytes());
    request
}

#[derive(Clone, Default)]
pub struct RealVerifier {
    pub calls: Arc<AtomicUsize>,
}

impl AccountProofVerifier for RealVerifier {
    fn scope(&self) -> AccountProofScope {
        record(0).proof_scope
    }

    fn verify(&self, statement: &AccountStatement, proof: &[u8]) -> Result<(), Error> {
        self.calls.fetch_add(1, Ordering::SeqCst);
        // A test-process cache bounds repeat cryptographic work across the
        // storage cases. Every distinct exact statement/proof is verified by
        // the real worker before its result can be reused; mutations miss it.
        type Results = BTreeMap<Vec<u8>, Result<(), Error>>;
        static RESULTS: OnceLock<Mutex<Results>> = OnceLock::new();
        let key = serde_json::to_vec(&(statement, proof)).unwrap();
        let mut results = RESULTS.get_or_init(Mutex::default).lock().unwrap();
        if let Some(result) = results.get(&key) {
            return result.clone();
        }
        let config = ProcessVerifierConfig {
            node: std::env::split_paths(&std::env::var_os("PATH").unwrap())
                .map(|path| path.join("node"))
                .find(|path| path.is_absolute() && path.is_file())
                .unwrap(),
            script: PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("runtime/accounting/node-verifier.mjs"),
            artifact_config: directory().join("config.json"),
            scope: self.scope(),
            timeout: Duration::from_secs(180),
            maximum_parallel: 1,
            max_proof_bytes: 1024 * 1024,
            node_heap_megabytes: 2048,
        };
        let result = ProcessAccountVerifier::new(config)?.verify(statement, proof);
        results.insert(key, result.clone());
        result
    }
}
